### ISSUE TITLE
Package name?

### ISSUE THREAD

**Issue by jorainer** [LiesaSalzer/mobilityTransformationR#1]
Just a small comment - packages in Bioconductor usually are starting with a capital letter (at least there is sort of that convention, although not all follow that...) - so maybe it would make sense renaming the package to `MobilityTransformationR`?

(reason is that functions start with lower case, objects and packages with upper case letters...)

**Comment by LiesaSalzer** [comment]
Thanks for the suggestion! I changed it accordingly
